pipeline {
    agent {
        docker {
            image 'node:latest'
            args '-p 4201:4201'
        }
    }
    environment {
        CI = 'true'
    }
    stages {
        stage ('WarmingUp') {
          steps
          {
            slackSend color: "warning", message: "Hold your breath, the pipeline has started executing"
          }
        }
        stage('Build') {
            steps {
                slackSend color: "green", message: "Installing npm"
                sh 'npm install'
            }
            post {
              success {
                slackSend color: "good", message: "The build ${BUILD_NUMBER} has been completed successfully"
              }
              failure {
                slackSend color: "red", message: "The build ${BUILD_NUMBER} has thrown an error - check console output for more details"
              }
            }
        }
        stage('Test') {
            steps {
                slackSend color: "green", message: "Performing unit tests"
                sh './jenkins/scripts/test.sh'
            }
            post {
              success {
                slackSend color: "good", message: "The build ${BUILD_NUMBER} has been Tested - check log for details"
              }
              failure {
                slackSend color: "red", message: "The test execution found some error - check console output for more details"
              }
            }
        }
        stage('Deliver') {
            steps {
                slackSend color: "green", message: "Deploying the application"
                sh './jenkins/scripts/deliver.sh'
                 input message: 'Finished using the web site? (Click "Proceed" to continue)'
                 sh './jenkins/scripts/kill.sh'
            }
            post {
              success {
                slackSend color: "good", message: "The package/application has been delivered"
              }
              failure {
                slackSend color: "red", message: "Some error occurred in delivery step of the pipeline - check log for details"
              }
            }
        }
    }
}
